### ISSUE TITLE
Links to some appendices are not jumping to correct positions

### ISSUE THREAD

**Issue by zchenry** [untitled-ai/untitled-ai.github.io#1]
Thank you for your insightful work!

In this [post](https://untitled-ai.github.io/understanding-self-supervised-contrastive-learning.html), there are links to specific sections of appendices. However, only [the link to appendix A](https://untitled-ai.github.io/appendix-for-understanding-self-supervised-contrastive-learning.html#appendix-a) will jump to the corresponding appendix position.

I suppose this is because an anchor `<a name="appendix-a"></a>` is added only before the section of appendix A. Adding similar anchors before other appendix sections would solve the issue.

**Comment by abefetterman** [comment]
Thanks a lot for the report! I've fixed the links now.
